name: alphapy

channels:
 - conda-forge

dependencies:
- bokeh>=0.12
- ipython>=3.2.3
- matplotlib>=2.0.0
- numpy>=1.9.1
- pandas>=0.22.0
- pyyaml>=3.12
- scikit-learn>=0.17.1
- scipy>=0.18.1
- seaborn>=0.7.1
- xgboost>=0.6a2
- pip:
  - category_encoders>=1.2.0
  - imbalanced-learn>=0.2.1
  - pandas-datareader>=0.3
  - pyfolio>=0.7